## Online Retail Data Set: Simulation

To do list

- index one of the columns in the dataset
- what is the mean, median for unit price
- unit price missing .00

### 3. Synthesise/simulate a data set as closely matching their properties as possible.

In [12]:
# import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

size=200

### StockCode
Generate a code with five digits and an uppercase letter. Example: 85123A

In [2]:
import string
# create list of uppercase letters
letterlist = list(string.ascii_uppercase)
letters= np.random.choice(letterlist, size=size)

number = np.random.choice(a=range(536365,541690), size=size)

# create an empty array for stockcode
stockcode = []

for i in range(len(number)):
    stockcode.append(str(number[i])+ str(letters[i]))
print(stockcode)

['537466F', '540620J', '537275D', '536912L', '537949Y', '541507O', '537808Y', '539883J', '540290E', '540686M', '536795I', '540572N', '541145A', '536527H', '536618M', '541167M', '541028T', '538568T', '539081D', '541235J', '541075Z', '537460F', '539931W', '538028P', '538724M', '540469T', '537481Y', '536470P', '536741W', '537758N', '537454F', '537100B', '538491R', '540589C', '540077Y', '539911E', '540515E', '536942Y', '538990Z', '540131L', '538898C', '541195M', '541055B', '541484H', '537632Z', '540534E', '536748G', '536395Q', '540030K', '538885B', '537388W', '536544H', '541326B', '539724Y', '538955R', '537256C', '540057C', '541452H', '537999A', '539711S', '540362W', '540849T', '538290B', '540137J', '538543Z', '536937L', '540448H', '537961Q', '539953C', '540295O', '540942X', '541168P', '540222B', '537025X', '541121E', '537565N', '539237T', '539443P', '539620Q', '540435L', '540019W', '537518T', '536781R', '538420M', '539492N', '536393L', '536967D', '538962G', '537949V', '538766Z', '540573V'

### Description
Generate Description name from the strings available and duplicate 

In [3]:
data = ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN' , 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE',
'RED WOOLLY HOTTIE WHITE HEART', 'SET 7 BABUSHKA NESTING BOXES','GLASS STAR FROSTED T-LIGHT HOLDER'
'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT' , 'POPPY PLAYHOUSE BEDROOM', 'PLAYHOUSE KITCHEN',
'FELTCRAFT PRINCESS CHARLOTTE DOLL','IVORY KNITTED MUG COSY','BOX OF 6 ASSORTED COLOUR TEASPOONS',
'BOX OF VINTAGE JIGSAW BLOCKS','BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD',
'LOVE BUILDING BLOCK WORD','DOORMAT NEW ENGLAND','JAM MAKING SET WITH JARS',
'RED COAT RACK PARIS FASHION','YELLOW COAT RACK PARIS FASHION','BLUE COAT RACK PARIS FASHION','BATH BUILDING BLOCK WORD']

description = [np.random.choice(data) for i in range(size)]

### InvoiceNo
Generate a six digit number e.g 536365

In [4]:
invoice = np.random.choice(a=range(536365,541690), size=size)
invoice

array([539616, 539840, 540071, 537957, 541047, 540087, 538429, 537758,
       540439, 541115, 539533, 537220, 537087, 538223, 541225, 537763,
       539064, 541226, 536638, 536549, 538245, 539098, 536687, 541012,
       536744, 539638, 541315, 536654, 540803, 537823, 541170, 536561,
       540209, 538854, 538299, 541564, 538454, 539371, 536720, 538374,
       540146, 541687, 537095, 540101, 539153, 537124, 536474, 540940,
       537657, 537141, 538387, 539731, 541413, 537856, 540435, 541225,
       541214, 541006, 537710, 536611, 541087, 537565, 536604, 537601,
       539715, 540489, 541186, 541607, 540520, 537323, 541537, 539512,
       538115, 540047, 537961, 540918, 537067, 538958, 536515, 540592,
       538896, 541296, 537779, 539801, 538664, 540474, 537067, 537560,
       540916, 540644, 541478, 537091, 540257, 540820, 539624, 541555,
       538585, 541210, 536468, 539137, 536886, 537077, 536828, 539122,
       539859, 536635, 537465, 538288, 536753, 537708, 540636, 536372,
      

### CustomerID
Generate a five digit number. Example: 17850

In [5]:
CustomerID = np.random.choice(a=range(12583, 17850), size=size)
CustomerID

array([15897, 17541, 14474, 17590, 17821, 14443, 14876, 12970, 16334,
       13787, 13998, 14065, 16036, 15317, 17061, 16487, 15292, 16578,
       13320, 17255, 17086, 15599, 16296, 17451, 15936, 16256, 13958,
       12814, 15945, 15680, 16939, 16623, 16538, 17614, 16582, 15664,
       14489, 15638, 16862, 13285, 12690, 14774, 15363, 12948, 15558,
       15286, 14976, 15853, 14353, 15960, 12630, 14130, 15253, 12887,
       13336, 16837, 17447, 15363, 16573, 16850, 13134, 16806, 16427,
       13997, 13707, 16890, 15053, 14424, 13095, 17245, 17729, 16328,
       16907, 15761, 16630, 13058, 13979, 15846, 13287, 16261, 17480,
       15394, 13535, 12709, 17261, 14783, 13441, 16950, 14778, 17142,
       16576, 16709, 14157, 16752, 15545, 12593, 14109, 15295, 15490,
       14579, 15302, 16362, 13844, 14335, 13884, 15175, 16996, 14319,
       12985, 17289, 16203, 14042, 14987, 17622, 16475, 15465, 14674,
       16778, 16086, 15669, 12825, 14051, 13710, 13520, 12802, 14087,
       17519, 13188,

### Quantity	

Generate numbers for quantity. As 75% of the datapoints had a quantity of 12, I will generate the number between 1 and 14.

In [6]:
#Quantity
#count 39184.000000
#mean 14.616246
#std 378.059152
#25% 2.000000
#50% 5.000000
#75% 12.000000
#max 74215.000000

quantity = np.random.choice(a=range(1, 14), size=size)
quantity

array([ 2, 10, 10,  8, 11,  1, 11,  7,  4,  1,  4, 12, 12,  9,  4,  6,  5,
       10,  6,  4,  4,  7,  9,  8,  3,  1, 13, 11,  9,  4,  9, 12,  3, 13,
        4, 13,  8,  8, 10,  2,  6,  9, 11,  4, 11,  9,  6,  9, 13,  9,  4,
        4,  9,  2,  4, 12,  2,  6, 13,  3, 13, 10, 11, 13, 12,  6,  3,  1,
       10,  8,  8, 11,  8,  4, 10,  3,  8,  7,  5,  6,  8,  8,  8,  6, 10,
        4, 12, 11,  5, 13,  1,  6, 13, 13, 10,  7,  8, 12,  1, 13,  5,  4,
        6,  3,  4,  4,  3,  7,  5,  6,  3,  8,  7,  7,  6,  4, 11,  2,  2,
        5,  9,  4,  7,  5,  5, 12,  8,  2, 11,  4, 11,  9, 13, 12,  3, 13,
       10,  7, 11,  4,  7,  5,  2, 12,  4,  1,  9,  2,  7,  3,  9,  3,  9,
       11,  2, 10,  4,  1,  5,  7,  6,  2,  5,  8,  7,  5,  2,  3,  4,  6,
        9,  2,  5,  1,  7, 12,  5, 10, 11,  7,  6,  5,  6,  9, 12,  3,  6,
        7,  7,  5, 11,  6,  6,  6,  2,  2,  2,  8, 13,  1])

### Unit Price

Generate a number with two digits to replicate the unit price. For example: 2.55

In [7]:
unitprice = np.round(np.random.normal(loc=2.90, scale=0.5, size=size), 2)
unitprice

array([3.78, 2.6 , 3.19, 2.71, 2.12, 3.02, 2.26, 2.89, 2.64, 3.75, 3.96,
       3.14, 3.47, 3.09, 2.27, 2.38, 2.98, 3.23, 2.91, 3.16, 3.34, 2.81,
       2.43, 2.43, 2.22, 2.45, 3.22, 2.51, 2.61, 3.21, 3.85, 2.39, 1.78,
       2.33, 2.7 , 3.02, 2.55, 3.44, 1.57, 2.56, 2.47, 3.23, 3.17, 3.1 ,
       3.05, 2.79, 2.15, 2.75, 2.61, 3.79, 3.21, 2.9 , 2.51, 3.4 , 2.64,
       3.95, 3.46, 2.97, 2.08, 2.88, 3.3 , 1.86, 3.39, 2.3 , 3.04, 2.91,
       3.95, 2.2 , 3.35, 3.22, 2.59, 2.63, 3.3 , 3.47, 2.19, 2.77, 2.56,
       3.16, 2.81, 3.02, 2.6 , 3.14, 3.6 , 2.77, 2.56, 3.06, 3.99, 3.16,
       2.74, 2.59, 2.74, 2.5 , 3.51, 3.76, 2.79, 3.44, 2.33, 3.94, 2.42,
       3.31, 2.57, 2.76, 3.31, 3.79, 3.39, 3.25, 2.59, 2.09, 2.19, 2.8 ,
       2.06, 2.92, 3.43, 3.46, 2.43, 2.99, 2.82, 2.4 , 2.47, 2.74, 2.72,
       2.72, 3.19, 2.6 , 3.  , 3.9 , 2.87, 2.96, 3.38, 2.95, 2.2 , 3.26,
       3.34, 3.91, 3.77, 2.7 , 3.02, 3.36, 3.07, 2.56, 3.42, 3.56, 2.57,
       2.69, 3.12, 2.9 , 3.72, 2.68, 3.57, 2.49, 2.

### Invoice Date

Generate Date range between the dates: 12/01/2010 and 01/31/2011. Example: 2010-12-01 08:26:00, rounded to minute

In [17]:
# adapted from https://pandas.pydata.org/pandas-docs/stable/timeseries.html
rng = pd.date_range('12/01/2010', '01/31/2011', periods=size)

# To remove the extra decimal places
invoicedatedata = pd.Series(rng).dt.round("min")
invoicedatedata

0     2010-12-01 00:00:00
1     2010-12-01 07:21:00
2     2010-12-01 14:43:00
3     2010-12-01 22:04:00
4     2010-12-02 05:26:00
5     2010-12-02 12:47:00
6     2010-12-02 20:08:00
7     2010-12-03 03:30:00
8     2010-12-03 10:51:00
9     2010-12-03 18:13:00
10    2010-12-04 01:34:00
11    2010-12-04 08:55:00
12    2010-12-04 16:17:00
13    2010-12-04 23:38:00
14    2010-12-05 07:00:00
15    2010-12-05 14:21:00
16    2010-12-05 21:43:00
17    2010-12-06 05:04:00
18    2010-12-06 12:25:00
19    2010-12-06 19:47:00
20    2010-12-07 03:08:00
21    2010-12-07 10:30:00
22    2010-12-07 17:51:00
23    2010-12-08 01:12:00
24    2010-12-08 08:34:00
25    2010-12-08 15:55:00
26    2010-12-08 23:17:00
27    2010-12-09 06:38:00
28    2010-12-09 13:59:00
29    2010-12-09 21:21:00
              ...        
170   2011-01-22 02:39:00
171   2011-01-22 10:01:00
172   2011-01-22 17:22:00
173   2011-01-23 00:43:00
174   2011-01-23 08:05:00
175   2011-01-23 15:26:00
176   2011-01-23 22:48:00
177   2011-0

### Country
Generate Country from the list of 22 countries

In [18]:
country = ['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain']

countries = [np.random.choice(country) for i in range(size)]

### 4. Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook.

### Creating a Dataframe

In [19]:
mydict = { "InvoiceNo":invoice, "StockCode":stockcode, "Description": description, 'Quantity': quantity, 
          "InvoiceDate":invoicedatedata, 'UnitPrice':unitprice, "CustomerID":CustomerID, "Country":countries}

df = pd.DataFrame(mydict, 
                  columns=['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'])

df

InvoiceNo StockCode                                        Description  \
0       539616   537466F  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
1       539840   540620J                          HAND WARMER RED POLKA DOT   
2       540071   537275D                           JAM MAKING SET WITH JARS   
3       537957   536912L                       SET 7 BABUSHKA NESTING BOXES   
4       541047   537949Y                  FELTCRAFT PRINCESS CHARLOTTE DOLL   
5       540087   541507O                       SET 7 BABUSHKA NESTING BOXES   
6       538429   537808Y  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
7       537758   539883J                     BOX OF VINTAGE ALPHABET BLOCKS   
8       540439   540290E                      RED WOOLLY HOTTIE WHITE HEART   
9       541115   540686M                        RED COAT RACK PARIS FASHION   
10      539533   536795I                             IVORY KNITTED MUG COSY   
11      537220   540572N                                WHITE METAL LANTERN   
12      537087   541145A                                WHITE METAL LANTERN   
13      538223   536527H                     YELLOW COAT RACK PARIS FASHION   
14      541225   536618M                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
15      537763   541167M                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
16      539064   541028T                 WHITE HANGING HEART T-LIGHT HOLDER   
17      541226   538568T                        RED COAT RACK PARIS FASHION   
18      536638   539081D                           JAM MAKING SET WITH JARS   
19      536549   541235J                           HOME BUILDING BLOCK WORD   
20      538245   541075Z                     BOX OF VINTAGE ALPHABET BLOCKS   
21      539098   537460F                     CREAM CUPID HEARTS COAT HANGER   
22      536687   539931W                  FELTCRAFT PRINCESS CHARLOTTE DOLL   
23      541012   538028P                            POPPY PLAYHOUSE BEDROOM   
24      536744   538724M                           JAM MAKING SET WITH JARS   
25      539638   540469T                 WHITE HANGING HEART T-LIGHT HOLDER   
26      541315   537481Y                 WHITE HANGING HEART T-LIGHT HOLDER   
27      536654   536470P                      ASSORTED COLOUR BIRD ORNAMENT   
28      540803   536741W                     YELLOW COAT RACK PARIS FASHION   
29      537823   537758N                        RED COAT RACK PARIS FASHION   
..         ...       ...                                                ...   
170     541356   539106F                          HAND WARMER RED POLKA DOT   
171     539941   541007E                            POPPY PLAYHOUSE BEDROOM   
172     538511   538765Q                           LOVE BUILDING BLOCK WORD   
173     537453   541007G                          HAND WARMER RED POLKA DOT   
174     537740   537179S                     CREAM CUPID HEARTS COAT HANGER   
175     540443   541548G                       SET 7 BABUSHKA NESTING BOXES   
176     540935   538674O                           BATH BUILDING BLOCK WORD   
177     539695   538869Y                            POPPY PLAYHOUSE BEDROOM   
178     539090   537392E                          HAND WARMER RED POLKA DOT   
179     537694   540205V                     BOX OF VINTAGE ALPHABET BLOCKS   
180     541641   536446I                                  PLAYHOUSE KITCHEN   
181     537919   540841G                           BATH BUILDING BLOCK WORD   
182     537204   539326B                KNITTED UNION FLAG HOT WATER BOTTLE   
183     540708   540186I                       SET 7 BABUSHKA NESTING BOXES   
184     539076   540867U                     YELLOW COAT RACK PARIS FASHION   
185     539207   536574R                       BLUE COAT RACK PARIS FASHION   
186     536660   541330S                     CREAM CUPID HEARTS COAT HANGER   
187     537680   537708P                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
188     540107   538238A                 WHITE HANGING 