## Online Retail Data Set: Simulation

To do list

- index one of the columns in the dataset
- what is the mean, median for unit price

### 3. Synthesise/simulate a data set as closely matching their properties as possible.

In [1]:
# import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

size=100

### StockCode
Generate a code with five digits and an uppercase letter. Example: 85123A

In [62]:
import string
# create list of uppercase letters
letterlist = list(string.ascii_uppercase)
letters= np.random.choice(letterlist, size=size)

number = np.random.choice(a=range(536365,541690), size=size)

# create an empty array for stockcode
stockcode = []

for i in range(len(number)):
    stockcode.append(str(number[i])+ str(letters[i]))
print(stockcode)

['538659Q', '536416P', '540868A', '540406J', '540472Z', '538479K', '538645B', '538522R', '537617L', '541594N', '537790K', '538136L', '539600S', '537259Z', '538597T', '536441G', '538582A', '538353D', '538399I', '540077V', '539909P', '537570K', '537360T', '536855U', '539849R', '540037Z', '539202A', '540870C', '537630B', '538319W', '536891N', '539498R', '540580C', '539374A', '539532T', '541133F', '537886S', '537733C', '541380X', '540810K', '539870J', '541497L', '540039Z', '538558J', '541586H', '541292V', '538473P', '539109R', '541071U', '539721R', '540800D', '538587B', '539572K', '536534Z', '540516C', '537896N', '538739U', '540644I', '538478R', '541607I', '540251H', '538064R', '539029F', '538027S', '539993K', '538194C', '536968D', '540272E', '538704U', '539466S', '539288B', '538308M', '540594U', '541535R', '540876F', '539172S', '536840E', '536818C', '540536K', '541352B', '540148R', '536526F', '538738W', '540756V', '541099J', '538935G', '540845J', '537096U', '538291H', '540660J', '537457I'

### Description
Generate Description name from the strings available and duplicate 

In [6]:
data = ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN' , 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE',
'RED WOOLLY HOTTIE WHITE HEART', 'SET 7 BABUSHKA NESTING BOXES','GLASS STAR FROSTED T-LIGHT HOLDER'
'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT' , 'POPPY PLAYHOUSE BEDROOM', 'PLAYHOUSE KITCHEN',
'FELTCRAFT PRINCESS CHARLOTTE DOLL','IVORY KNITTED MUG COSY','BOX OF 6 ASSORTED COLOUR TEASPOONS',
'BOX OF VINTAGE JIGSAW BLOCKS','BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD',
'LOVE BUILDING BLOCK WORD','DOORMAT NEW ENGLAND','JAM MAKING SET WITH JARS',
'RED COAT RACK PARIS FASHION','YELLOW COAT RACK PARIS FASHION','BLUE COAT RACK PARIS FASHION','BATH BUILDING BLOCK WORD']

description = [np.random.choice(data) for i in range(size)]

### InvoiceNo
Generate a six digit number e.g 536365

In [7]:
invoice = np.random.choice(a=range(536365,541690), size=size)
invoice

array([541025, 536811, 541339, 536588, 540198, 538234, 539843, 538301,
       540112, 538150, 536372, 541669, 538649, 541214, 540528, 540276,
       536534, 536729, 539773, 537460, 541551, 541443, 536726, 539146,
       538558, 537310, 539310, 540073, 537660, 541571, 540647, 536516,
       537381, 540583, 540963, 540979, 540563, 541137, 537088, 537916,
       537984, 539668, 537627, 541631, 536977, 541512, 537220, 537357,
       540617, 541201, 539910, 541068, 539777, 539735, 536884, 537471,
       541291, 537407, 536791, 536641, 540713, 538912, 538894, 541643,
       538416, 538694, 536772, 538335, 539338, 541343, 539588, 539681,
       537750, 536729, 536373, 538469, 540819, 538416, 539729, 537761,
       541185, 536590, 541274, 541610, 541652, 538056, 540881, 541209,
       541325, 541559, 540778, 536518, 539984, 537768, 538112, 540986,
       539838, 540055, 541463, 536925])

### CustomerID
Generate a five digit number. Example: 17850

In [8]:
CustomerID = np.random.choice(a=range(12583, 17850), size=size)
CustomerID

array([15177, 13459, 12683, 14277, 12751, 17648, 14168, 13015, 13328,
       14021, 16301, 13777, 14510, 12801, 15704, 15223, 14003, 16728,
       16498, 14503, 15965, 13029, 15653, 16517, 15700, 17700, 14414,
       15466, 14949, 17104, 14297, 14675, 14619, 14006, 17548, 13684,
       17649, 14438, 14324, 14541, 15605, 13648, 15679, 15474, 14904,
       13875, 15189, 15912, 14619, 13114, 12943, 15569, 12988, 13909,
       15290, 12919, 13809, 13493, 15596, 16397, 12959, 12732, 16302,
       14127, 15845, 14027, 14791, 13620, 14900, 13187, 17726, 12832,
       13767, 15157, 16970, 15368, 15239, 17608, 14985, 15268, 15237,
       13719, 13826, 13775, 12900, 16893, 16622, 17831, 16338, 15793,
       14341, 17527, 14347, 15930, 17104, 13511, 15434, 17782, 15372,
       12946])

### Quantity	

Generate numbers for quantity. As 75% of the datapoints had a quantity of 12, I will generate the number between 1 and 14.

In [9]:
#Quantity
#count 39184.000000
#mean 14.616246
#std 378.059152
#25% 2.000000
#50% 5.000000
#75% 12.000000
#max 74215.000000

quantity = np.random.choice(a=range(1, 14), size=size)
quantity

array([ 6,  1, 12, 12,  7,  9,  3, 10,  4,  6, 10,  3,  3,  3,  3, 12,  5,
       11,  1, 10,  3,  5,  2,  1,  7,  8,  4,  4,  6,  2, 12,  4,  1,  9,
       12, 13,  1,  4,  7,  4,  9,  8,  5, 10,  1,  7,  4,  7,  6, 12,  3,
        2,  5,  5,  3, 12, 11, 11,  4,  9, 11,  1, 10,  5, 13,  7, 13, 11,
        2,  5, 11, 11, 11,  4, 11, 12,  7, 11,  4,  3,  9,  9, 12, 11,  7,
       10, 12,  2, 13, 11,  1, 13,  2,  9, 10,  4,  8,  8, 11, 12])

### Unit Price

Generate a number with two digits to replicate the unit price. For example: 2.55

In [10]:
unitprice = np.round(np.random.normal(loc=2.90, scale=0.5, size=size), 2)
unitprice

array([2.79, 3.34, 3.02, 2.76, 2.32, 2.61, 3.49, 2.61, 2.94, 2.01, 2.44,
       3.05, 3.59, 2.07, 3.17, 2.98, 2.97, 3.74, 2.56, 2.43, 3.25, 2.75,
       1.94, 3.96, 1.77, 2.54, 4.12, 3.06, 3.53, 3.66, 2.91, 3.31, 2.03,
       2.61, 2.59, 2.62, 2.44, 3.46, 2.96, 2.15, 3.  , 4.12, 2.77, 3.51,
       2.87, 2.82, 3.21, 3.22, 3.79, 3.4 , 3.05, 2.9 , 2.72, 2.49, 3.51,
       2.98, 2.53, 2.52, 2.83, 2.57, 2.54, 3.94, 2.88, 2.68, 2.49, 3.  ,
       2.61, 3.42, 2.55, 3.29, 2.68, 2.63, 2.98, 2.43, 3.01, 2.86, 2.84,
       3.08, 3.06, 2.95, 2.75, 2.53, 2.14, 3.58, 3.03, 3.13, 3.31, 3.  ,
       2.78, 4.04, 3.57, 2.08, 2.86, 2.68, 3.61, 2.59, 2.85, 2.45, 2.53,
       3.69])

### Invoice Date

Generate Date range between the dates: 12/01/2010 and 01/31/2011. Example: 2010-12-01 08:26:00

In [11]:
# adapted from https://pandas.pydata.org/pandas-docs/stable/timeseries.html
rng = pd.date_range('12/01/2010', '01/31/2011', periods=size)

# To remove the extra decimal places
invoicedatedata = pd.Series(rng).dt.round("s")
invoicedatedata

0    2010-12-01 00:00:00
1    2010-12-01 14:47:16
2    2010-12-02 05:34:33
3    2010-12-02 20:21:49
4    2010-12-03 11:09:05
5    2010-12-04 01:56:22
6    2010-12-04 16:43:38
7    2010-12-05 07:30:55
8    2010-12-05 22:18:11
9    2010-12-06 13:05:27
10   2010-12-07 03:52:44
11   2010-12-07 18:40:00
12   2010-12-08 09:27:16
13   2010-12-09 00:14:33
14   2010-12-09 15:01:49
15   2010-12-10 05:49:05
16   2010-12-10 20:36:22
17   2010-12-11 11:23:38
18   2010-12-12 02:10:55
19   2010-12-12 16:58:11
20   2010-12-13 07:45:27
21   2010-12-13 22:32:44
22   2010-12-14 13:20:00
23   2010-12-15 04:07:16
24   2010-12-15 18:54:33
25   2010-12-16 09:41:49
26   2010-12-17 00:29:05
27   2010-12-17 15:16:22
28   2010-12-18 06:03:38
29   2010-12-18 20:50:55
             ...        
70   2011-01-13 03:09:05
71   2011-01-13 17:56:22
72   2011-01-14 08:43:38
73   2011-01-14 23:30:55
74   2011-01-15 14:18:11
75   2011-01-16 05:05:27
76   2011-01-16 19:52:44
77   2011-01-17 10:40:00
78   2011-01-18 01:27:16


### Country
Generate Country from the list of 22 countries

In [12]:
country = ['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain']

countries = [np.random.choice(country) for i in range(size)]

### 4. Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook.

### Creating a Dataframe

In [63]:
mydict = { "InvoiceNo":invoice, "StockCode":stockcode, "Description": description, 'Quantity': quantity, 
          "InvoiceDate":invoicedatedata, 'UnitPrice':unitprice, "CustomerID":CustomerID, "Country":countries}

df = pd.DataFrame(mydict, 
                  columns=['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'])

df

InvoiceNo StockCode                                        Description  \
0      541025   538659Q                       BLUE COAT RACK PARIS FASHION   
1      536811   536416P                     YELLOW COAT RACK PARIS FASHION   
2      541339   540868A                                DOORMAT NEW ENGLAND   
3      536588   540406J                KNITTED UNION FLAG HOT WATER BOTTLE   
4      540198   540472Z  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
5      538234   538479K                     YELLOW COAT RACK PARIS FASHION   
6      539843   538645B                           LOVE BUILDING BLOCK WORD   
7      538301   538522R                           JAM MAKING SET WITH JARS   
8      540112   537617L                       BLUE COAT RACK PARIS FASHION   
9      538150   541594N                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
10     536372   537790K                     YELLOW COAT RACK PARIS FASHION   
11     541669   538136L                           HOME BUILDING BLOCK WORD   
12     538649   539600S                           LOVE BUILDING BLOCK WORD   
13     541214   537259Z                             IVORY KNITTED MUG COSY   
14     540528   538597T                      ASSORTED COLOUR BIRD ORNAMENT   
15     540276   536441G                           HOME BUILDING BLOCK WORD   
16     536534   538582A  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
17     536729   538353D                       BOX OF VINTAGE JIGSAW BLOCKS   
18     539773   538399I                KNITTED UNION FLAG HOT WATER BOTTLE   
19     537460   540077V                 WHITE HANGING HEART T-LIGHT HOLDER   
20     541551   539909P                           JAM MAKING SET WITH JARS   
21     541443   537570K                      RED WOOLLY HOTTIE WHITE HEART   
22     536726   537360T                           JAM MAKING SET WITH JARS   
23     539146   536855U                     YELLOW COAT RACK PARIS FASHION   
24     538558   539849R                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
25     537310   540037Z  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
26     539310   539202A                      RED WOOLLY HOTTIE WHITE HEART   
27     540073   540870C                           HOME BUILDING BLOCK WORD   
28     537660   537630B                      RED WOOLLY HOTTIE WHITE HEART   
29     541571   538319W                 WHITE HANGING HEART T-LIGHT HOLDER   
..        ...       ...                                                ...   
70     539588   539288B                     BOX OF VINTAGE ALPHABET BLOCKS   
71     539681   538308M                       SET 7 BABUSHKA NESTING BOXES   
72     537750   540594U                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
73     536729   541535R  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
74     536373   540876F                            POPPY PLAYHOUSE BEDROOM   
75     538469   539172S                 WHITE HANGING HEART T-LIGHT HOLDER   
76     540819   536840E                      RED WOOLLY HOTTIE WHITE HEART   
77     538416   536818C                      RED WOOLLY HOTTIE WHITE HEART   
78     539729   540536K                                DOORMAT NEW ENGLAND   
79     537761   541352B                            POPPY PLAYHOUSE BEDROOM   
80     541185   540148R                           LOVE BUILDING BLOCK WORD   
81     536590   536526F                        RED COAT RACK PARIS FASHION   
82     541274   538738W                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
83     541610   540756V                             IVORY KNITTED MUG COSY   
84     541652   541099J                     CREAM CUPID HEARTS COAT HANGER   
85     538056   538935G                     BOX OF VINTAGE ALPHABET BLOCKS   
86     540881   540845J                          HAND WARMER RED POLKA DOT   
87     541209   537096U                                  PLAYHOUSE KITCHEN   
88     541325   538291H                      RED WOOLLY HOTTIE WHITE HEART   
89     541559   540660J   