## Online Retail Data Set: Simulation

To do list

- index one of the columns in the dataset
- stockcode - generate
- should stockcode have an uppercase letter
- remove 0 numbers in quantity
- check where the date is coming from
- what is the mean, median for unit price

### 3. Synthesise/simulate a data set as closely matching their properties as possible.

In [1]:
# import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

size=100

### StockCode
Generate a code with five digits and an uppercase letter. Example: 85123A

In [2]:
import string
L = list(string.ascii_uppercase)
L

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [3]:
np.random.choice(a=range(536365,541690), size=size)

array([539677, 541503, 540436, 540990, 541261, 539713, 539963, 540558,
       537387, 538298, 539966, 541233, 536616, 541449, 538598, 539736,
       537469, 537575, 539206, 538380, 540268, 537280, 538680, 539380,
       538658, 540442, 539491, 537767, 539601, 540794, 539734, 539841,
       539257, 538467, 537737, 536702, 536970, 538670, 537504, 538570,
       539078, 540578, 539712, 539854, 539448, 540355, 538352, 539548,
       539402, 540449, 536481, 537792, 538682, 538878, 537487, 540183,
       540945, 540730, 537831, 538773, 539720, 537163, 536883, 536666,
       538800, 539075, 539686, 538786, 539168, 541239, 537742, 541323,
       540854, 538249, 537821, 537576, 539067, 540607, 541470, 539667,
       540139, 539232, 538684, 540764, 540279, 538493, 540846, 541447,
       537181, 538288, 539458, 539081, 540778, 539711, 541121, 538055,
       537805, 541111, 536925, 537365])

In [10]:
n = 6
''.join(["%s" % np.random.randint(1, 5) for num in range(0, n)])

'422324'

In [20]:
import string
import random
def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(6))

id_generator()


'GB25BF'

### Description
Generate Description name from the strings available and duplicate 

In [77]:
data = ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN' , 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE',
'RED WOOLLY HOTTIE WHITE HEART', 'SET 7 BABUSHKA NESTING BOXES','GLASS STAR FROSTED T-LIGHT HOLDER'
'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT' , 'POPPY PLAYHOUSE BEDROOM', 'PLAYHOUSE KITCHEN',
'FELTCRAFT PRINCESS CHARLOTTE DOLL','IVORY KNITTED MUG COSY','BOX OF 6 ASSORTED COLOUR TEASPOONS',
'BOX OF VINTAGE JIGSAW BLOCKS','BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD',
'LOVE BUILDING BLOCK WORD','DOORMAT NEW ENGLAND','JAM MAKING SET WITH JARS',
'RED COAT RACK PARIS FASHION','YELLOW COAT RACK PARIS FASHION','BLUE COAT RACK PARIS FASHION','BATH BUILDING BLOCK WORD']

description = [np.random.choice(data) for i in range(size)]

### InvoiceNo
Generate a six digit number e.g 536365

In [70]:
invoice = np.random.choice(a=range(536365,541690), size=size)
invoice

array([540635, 538634, 538375, 538475, 540840, 538346, 539221, 540265,
       538307, 537326, 538019, 541286, 538140, 537425, 541104, 541102,
       536582, 538932, 540884, 541423, 536573, 538437, 538881, 538355,
       538481, 537363, 538940, 536900, 538955, 538133, 539511, 536522,
       539587, 540228, 536657, 536587, 540124, 540792, 536956, 538177,
       536871, 539626, 538580, 541239, 539306, 539896, 541448, 538559,
       536760, 537224, 537808, 537341, 540064, 539960, 539109, 540425,
       541082, 539216, 537526, 539626, 540857, 539088, 540691, 541614,
       537588, 537606, 537509, 537915, 541277, 537519, 538067, 536976,
       540500, 539210, 536661, 537841, 538634, 538293, 539651, 539858,
       536817, 537243, 536773, 538881, 537600, 537030, 537885, 538484,
       537807, 540534, 538918, 539513, 541392, 537361, 538535, 538570,
       537375, 541611, 537406, 541482])

### CustomerID
Generate a five digit number. Example: 17850

In [65]:
CustomerID = np.random.choice(a=range(12583, 17850), size=size)
CustomerID

array([13823, 13620, 15134, 13325, 13667, 16330, 13145, 14786, 12945,
       13577, 13316, 17497, 17362, 13195, 13498, 13604, 17025, 12883,
       15980, 17603, 17074, 13718, 17484, 13948, 16116, 15129, 13754,
       13055, 15537, 15026, 16762, 16466, 15576, 16726, 12852, 13631,
       13194, 14963, 12771, 13397, 14675, 16782, 13569, 13588, 16434,
       14618, 15996, 13112, 15108, 15129, 16996, 15631, 15482, 14878,
       16128, 17235, 15780, 13188, 15407, 16801, 16828, 15207, 16052,
       13455, 16448, 12654, 12687, 17069, 16846, 17605, 12833, 16823,
       12744, 14280, 16734, 15486, 12704, 17744, 16668, 14501, 14410,
       13251, 15894, 14904, 15569, 17531, 12687, 14275, 13670, 13639,
       14537, 13483, 12965, 16762, 17256, 14565, 15887, 13062, 13150,
       15424])

### Quantity	

Generate numbers for quantity. As 75% of the datapoints had a quantity of 12, I will generate the number between 1 and 14

In [53]:
#Quantity
#count 39184.000000
#mean 14.616246
#std 378.059152
#25% 2.000000
#50% 5.000000
#75% 12.000000
#max 74215.000000

quantity = np.random.choice(14, size=size)
quantity

array([ 2, 11,  0,  8, 11,  0,  8, 12,  7, 12, 13, 10, 10, 13, 11,  7, 13,
        1,  7,  9,  8,  1,  4, 13,  6,  3,  5,  6,  6,  3,  3,  4,  4, 13,
        0, 11,  2,  5,  5,  7,  9, 11, 10, 10,  0,  6, 13,  6,  2,  2, 12,
        7,  5,  7,  0, 12,  6, 11, 11,  9, 13,  8,  2,  0,  7,  0, 11,  6,
        8,  4,  3, 11,  7,  1,  0,  5,  4,  7,  2,  8,  0, 11,  7,  7, 13,
        7,  8, 11,  0, 11,  4,  6,  5,  8, 10,  0, 11,  9,  6,  5])

### Unit Price

Generate a number with two digits to replicate the unit price. For example: 2.55

In [54]:
unitprice = np.round(np.random.normal(loc=2.90, scale=0.5, size=size), 2)
unitprice

array([2.58, 2.28, 2.76, 3.19, 2.92, 2.76, 3.02, 3.1 , 3.23, 3.1 , 3.33,
       2.26, 2.14, 2.81, 2.86, 3.05, 2.59, 3.14, 2.46, 2.97, 3.58, 2.89,
       2.87, 2.93, 2.83, 3.17, 2.51, 2.68, 2.49, 3.38, 2.69, 2.33, 3.25,
       2.68, 2.4 , 2.42, 3.35, 3.51, 3.51, 3.24, 2.57, 2.27, 3.47, 2.96,
       3.04, 2.29, 2.49, 2.23, 2.66, 3.  , 2.54, 3.21, 1.96, 3.75, 3.11,
       2.4 , 3.07, 3.58, 2.87, 2.8 , 3.54, 2.87, 2.54, 2.91, 3.23, 3.07,
       3.06, 2.22, 2.61, 3.17, 2.82, 2.64, 3.34, 2.96, 2.91, 2.99, 3.3 ,
       2.99, 2.56, 3.55, 2.2 , 3.17, 2.1 , 3.7 , 2.99, 3.27, 3.  , 2.57,
       3.24, 2.81, 2.98, 2.69, 2.53, 2.66, 2.09, 2.72, 3.06, 2.91, 4.1 ,
       2.44])

### Invoice Date

Generate Date range between the dates: 12/01/2010 and 01/31/2011. Example: 2010-12-01 08:26:00

In [44]:
# adapted from https://pandas.pydata.org/pandas-docs/stable/timeseries.html
rng = pd.date_range('12/01/2010', '01/31/2011', freq='H')

### Country
Generate Country from the list of 22 countries

In [6]:
country = ['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain']

countries = [np.random.choice(country) for i in range(size)]
countries

['Austria',
 'Japan',
 'Netherlands',
 'Portugal',
 'Lithuania',
 'France',
 'Italy',
 'United Kingdom',
 'Iceland',
 'Austria',
 'Netherlands',
 'Belgium',
 'EIRE',
 'Finland',
 'France',
 'Bahrain',
 'United Kingdom',
 'Japan',
 'Israel',
 'Italy',
 'Netherlands',
 'Austria',
 'Australia',
 'Sweden',
 'Germany',
 'Spain',
 'Cyprus',
 'EIRE',
 'Channel Islands',
 'Spain',
 'France',
 'Belgium',
 'Israel',
 'Netherlands',
 'Denmark',
 'Netherlands',
 'Finland',
 'Belgium',
 'Lithuania',
 'Iceland',
 'Switzerland',
 'Sweden',
 'Austria',
 'Portugal',
 'France',
 'Australia',
 'Channel Islands',
 'Japan',
 'Spain',
 'Germany',
 'Australia',
 'Israel',
 'Cyprus',
 'Finland',
 'Denmark',
 'Denmark',
 'Italy',
 'Poland',
 'Portugal',
 'Australia',
 'Portugal',
 'Norway',
 'France',
 'Lithuania',
 'Switzerland',
 'Denmark',
 'Switzerland',
 'Belgium',
 'Israel',
 'Japan',
 'Germany',
 'Israel',
 'United Kingdom',
 'Israel',
 'Australia',
 'Switzerland',
 'Belgium',
 'Japan',
 'Belgium',
 'Li

### Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook.

### Creating a Dataframe

In [75]:
mydict = { "InvoiceNo":invoice, "Description": description, 'Quantity': quantity, 
          "InvoiceDate":InvoiceDate, 'UnitPrice':unitprice, "CustomerID":CustomerID, "Country":countries}

df = pd.DataFrame(mydict, 
                  columns=['InvoiceNo', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'])

df

InvoiceNo                                        Description  Quantity  \
0      540635                                  PLAYHOUSE KITCHEN         2   
1      538634                KNITTED UNION FLAG HOT WATER BOTTLE        11   
2      538375                        RED COAT RACK PARIS FASHION         0   
3      538475                KNITTED UNION FLAG HOT WATER BOTTLE         8   
4      540840                                  PLAYHOUSE KITCHEN        11   
5      538346                 BOX OF 6 ASSORTED COLOUR TEASPOONS         0   
6      539221                  FELTCRAFT PRINCESS CHARLOTTE DOLL         8   
7      540265                       BLUE COAT RACK PARIS FASHION        12   
8      538307                           JAM MAKING SET WITH JARS         7   
9      537326                      RED WOOLLY HOTTIE WHITE HEART        12   
10     538019                        RED COAT RACK PARIS FASHION        13   
11     541286                      ASSORTED COLOUR BIRD ORNAMENT        10   
12     538140                           BATH BUILDING BLOCK WORD        10   
13     537425  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...        13   
14     541104                       BLUE COAT RACK PARIS FASHION        11   
15     541102                       BLUE COAT RACK PARIS FASHION         7   
16     536582                                  PLAYHOUSE KITCHEN        13   
17     538932                KNITTED UNION FLAG HOT WATER BOTTLE         1   
18     540884                 BOX OF 6 ASSORTED COLOUR TEASPOONS         7   
19     541423                       BLUE COAT RACK PARIS FASHION         9   
20     536573                KNITTED UNION FLAG HOT WATER BOTTLE         8   
21     538437                          HAND WARMER RED POLKA DOT         1   
22     538881                     CREAM CUPID HEARTS COAT HANGER         4   
23     538355                           BATH BUILDING BLOCK WORD        13   
24     538481                        RED COAT RACK PARIS FASHION         6   
25     537363                KNITTED UNION FLAG HOT WATER BOTTLE         3   
26     538940                                  PLAYHOUSE KITCHEN         5   
27     536900                           HOME BUILDING BLOCK WORD         6   
28     538955                           JAM MAKING SET WITH JARS         6   
29     538133                      ASSORTED COLOUR BIRD ORNAMENT         3   
..        ...                                                ...       ...   
70     538067                          HAND WARMER RED POLKA DOT         3   
71     536976                      ASSORTED COLOUR BIRD ORNAMENT        11   
72     540500                           BATH BUILDING BLOCK WORD         7   
73     539210                      RED WOOLLY HOTTIE WHITE HEART         1   
74     536661                        RED COAT RACK PARIS FASHION         0   
75     537841                     CREAM CUPID HEARTS COAT HANGER         5   
76     538634                           LOVE BUILDING BLOCK WORD         4   
77     538293                             IVORY KNITTED MUG COSY         7   
78     539651                     CREAM CUPID HEARTS COAT HANGER         2   
79     539858                KNITTED UNION FLAG HOT WATER BOTTLE         8   
80     536817                           JAM MAKING SET WITH JARS         0   
81     537243                          HAND WARMER RED POLKA DOT        11   
82     536773                        RED COAT RACK PARIS FASHION         7   
83     538881                       BLUE COAT RACK PARIS FASHION         7   
84     537600                        RED COAT RACK PARIS FASHION        13   
85     537030                      RED WOOLLY HOTTIE WHITE HEART         7   
86     537885                      ASSORTED COLOUR BIRD ORNAMENT         8   
87     538484                       BLUE COAT RACK PARIS FASHION        11   
88     537807  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...         0   
89     540534             

In [50]:
import numpy as np
import pandas as pd

# reproducibility
np.random.seed(10)

# number of observations
size = 5000

# feature setup
degree = np.random.choice(a=range(4), size=size)
age = np.random.choice(a=range(18,61), size=size)
gender = np.random.choice(a=range(2), size=size)
major = np.random.choice(a=range(8), size=size)
gpa = np.round(np.random.normal(loc=2.90, scale=0.5, size=size), 2)
experience = None  
bootcamp = np.random.choice(a=range(2), size=size)
github = np.random.choice(a=range(21), size=size)
blogger = np.random.choice(a=range(2), size=size)
articles = 0  
t1, t2, t3, t4, t5 = None, None, None, None, None
hired = 0

In [31]:
mydict = {"degree":degree, "age":age, 
          "gender":gender, "major":major, 
          "gpa":gpa, "experience":experience, 
          "github":github, "bootcamp":bootcamp, 
          "blogger":blogger, "articles":articles,
          "t1":t1, "t2":t2, "t3":t3, "t4":t4, "t5":t5, "hired":hired}

df = pd.DataFrame(mydict,
                  columns=["degree", "age", "gender", "major", "gpa", 
                           "experience", "bootcamp", "github", "blogger", "articles",
                           "t1", "t2", "t3", "t4", "t5", "hired"])
df

degree  age  gender  major   gpa experience  bootcamp  github  blogger  \
0          1   25       1      5  1.90        NaN         0      15        0   
1          1   21       0      0  2.68        NaN         0      17        0   
2          0   45       1      6  3.49        NaN         0      20        1   
3          3   54       1      5  2.47        NaN         1       6        0   
4          0   51       1      7  2.08        NaN         0       5        1   
5          1   53       1      3  3.71        NaN         1      18        0   
6          3   60       1      0  2.84        NaN         0      14        0   
7          0   52       0      7  2.23        NaN         0      19        0   
8          1   34       1      0  2.88        NaN         0      18        0   
9          1   49       0      2  2.66        NaN         0      12        1   
10         0   39       0      0  3.47        NaN         1       0        0   
11         1   36       1      7  2.38        NaN         1      20        0   
12         1   28       0      3  3.08        NaN         1      18        0   
13         2   29       0      6  3.24        NaN         1      12        1   
14         0   40       1      6  2.36        NaN         1      11        0   
15         1   27       0      5  2.46        NaN         0      18        1   
16         0   23       0      7  3.03        NaN         0      17        1   
17         2   24       0      0  3.59        NaN         1       6        0   
18         0   28       0      3  1.94        NaN         0      14        1   
19         2   58       0      0  2.69        NaN         1      13        1   
20         0   25       1      3  3.09        NaN         1      11        0   
21         3   34       0      4  2.21        NaN         0      18        1   
22         0   44       0      0  3.35        NaN         0      16        1   
23         0   49       1      1  3.27        NaN         0       1        1   
24         3   21       1      0  3.51        NaN         1       8        0   
25         3   25       1      0  2.15        NaN         0      20        1   
26         2   35       1      3  2.66        NaN         0      12        1   
27         0   46       0      4  2.12        NaN         1      19        0   
28         3   33       0      6  2.43        NaN         1       7        1   
29         2   24       0      3  3.61        NaN         0      20        1   
...      ...  ...     ...    ...   ...        ...       ...     ...      ...   
4970       2   30       0      3  3.37        NaN         0      12        1   
4971       1   36       1      4  2.04        NaN         1      12        0   
4972       3   39       0      0  3.04        NaN         1       7        0   
4973       3   50       0      1  3.52        NaN         1       3        0   
4974       0   19       1      1  2.73        NaN         0       4        1   
4975       0   27       0      3  2.98        NaN         1      11        1   
4976       3   56       1      3  2.97        NaN         1       1        1   
4977       0   35       0      1  2.63        NaN         0      14        1   
4978       2   60       0      2  2.47        NaN         1       6        0   
4979       2   20       0      1  3.04        NaN         0      12        1   
4980       1   33       1      0  1.59        NaN         0       1        1   
4981       3   19       1      0  3.19        NaN         1      14        0   
4982       2   60       1      3  3.03        NaN         1      20        0   
4983       1   59       1      7  3.07        NaN         1      17        1   
4984       3   18       0      5  3.59        NaN         1       3        1   
4985       3   60       1      6  2.15        NaN         1      15        1   
4986       2   46       0      6  2.12        NaN         0       9        0   
4987       2   22       1      5  3.02        NaN         1      10        1   
4988  