## Online Retail Data Set: Simulation

To do list

- index one of the columns in the dataset
- stockcode - generate
- should stockcode have an uppercase letter
- what is the mean, median for unit price

### 3. Synthesise/simulate a data set as closely matching their properties as possible.

In [44]:
# import libraries
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

size=100

### StockCode
Generate a code with five digits and an uppercase letter. Example: 85123A

In [18]:
import string
L = list(string.ascii_uppercase)
L

['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [4]:
np.random.choice(a=range(536365,541690), size=size)

array([540481, 537898, 539697, 540307, 540252, 540557, 541689, 538574,
       539847, 539340, 537387, 541315, 536849, 540987, 540296, 538312,
       538471, 538222, 540973, 537021, 536643, 536762, 538736, 539808,
       539836, 537338, 538013, 536839, 537361, 541414, 541093, 541480,
       536637, 538777, 537023, 538658, 541332, 540223, 540134, 537408,
       536668, 541236, 538847, 540295, 537477, 539761, 540646, 541578,
       540597, 541570, 537254, 538974, 540416, 536436, 540031, 540342,
       539811, 539689, 540451, 541122, 537594, 539941, 540777, 539093,
       541209, 537324, 540677, 537039, 539223, 538796, 536642, 540888,
       540721, 539024, 541068, 541502, 541325, 541276, 541076, 540804,
       538058, 537447, 539393, 537126, 539069, 536862, 537159, 539785,
       540156, 541213, 541664, 538205, 537660, 540409, 536704, 539173,
       541632, 541055, 541482, 537382])

In [5]:
n = 6
''.join(["%s" % np.random.randint(1, 5) for num in range(0, n)])

'134241'

In [6]:
import string
import random
def id_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(6))

id_generator()


'YKOQ7G'

### Description
Generate Description name from the strings available and duplicate 

In [7]:
data = ['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN' , 'CREAM CUPID HEARTS COAT HANGER', 'KNITTED UNION FLAG HOT WATER BOTTLE',
'RED WOOLLY HOTTIE WHITE HEART', 'SET 7 BABUSHKA NESTING BOXES','GLASS STAR FROSTED T-LIGHT HOLDER'
'HAND WARMER UNION JACK', 'HAND WARMER RED POLKA DOT', 'ASSORTED COLOUR BIRD ORNAMENT' , 'POPPY PLAYHOUSE BEDROOM', 'PLAYHOUSE KITCHEN',
'FELTCRAFT PRINCESS CHARLOTTE DOLL','IVORY KNITTED MUG COSY','BOX OF 6 ASSORTED COLOUR TEASPOONS',
'BOX OF VINTAGE JIGSAW BLOCKS','BOX OF VINTAGE ALPHABET BLOCKS', 'HOME BUILDING BLOCK WORD',
'LOVE BUILDING BLOCK WORD','DOORMAT NEW ENGLAND','JAM MAKING SET WITH JARS',
'RED COAT RACK PARIS FASHION','YELLOW COAT RACK PARIS FASHION','BLUE COAT RACK PARIS FASHION','BATH BUILDING BLOCK WORD']

description = [np.random.choice(data) for i in range(size)]

### InvoiceNo
Generate a six digit number e.g 536365

In [8]:
invoice = np.random.choice(a=range(536365,541690), size=size)
invoice

array([541432, 536550, 538789, 538386, 539141, 539225, 538685, 536647,
       537683, 540829, 536406, 538154, 540897, 537928, 539093, 539479,
       537396, 540887, 536768, 536646, 536541, 537221, 536407, 539349,
       537539, 537721, 539266, 540196, 538167, 537958, 539274, 537095,
       541598, 540175, 539767, 540611, 540687, 538394, 541321, 538311,
       537581, 539274, 541276, 538066, 541271, 536742, 537180, 540893,
       538537, 541441, 536900, 536681, 539871, 537214, 537001, 537826,
       541263, 538932, 537903, 540476, 538824, 540987, 537855, 541249,
       537294, 541380, 537026, 541651, 537099, 541688, 537319, 536613,
       541449, 537310, 540082, 537855, 539828, 539712, 539173, 539633,
       541131, 541441, 539371, 540904, 537826, 537796, 538472, 540702,
       536603, 540325, 537533, 536753, 537157, 537757, 540876, 538338,
       536438, 541030, 541414, 540204])

### CustomerID
Generate a five digit number. Example: 17850

In [9]:
CustomerID = np.random.choice(a=range(12583, 17850), size=size)
CustomerID

array([16763, 12752, 13247, 15575, 16976, 16077, 16018, 15130, 16044,
       15171, 17253, 17373, 13572, 14844, 15493, 14781, 13048, 17177,
       13185, 15351, 16670, 16611, 13387, 15108, 15279, 15103, 15532,
       15168, 15024, 13243, 15127, 14436, 16320, 15795, 16115, 14324,
       15404, 17381, 17742, 17142, 17351, 14536, 16738, 13746, 15147,
       13515, 17270, 15965, 14649, 14715, 14161, 16387, 14486, 13340,
       17044, 14272, 14146, 17621, 15319, 15068, 14323, 16888, 13899,
       16104, 17382, 14390, 14677, 15222, 16477, 16943, 13929, 16069,
       12792, 17594, 16015, 15358, 16112, 13667, 16473, 16734, 12975,
       16505, 15749, 15803, 17842, 12992, 13089, 12823, 17131, 17819,
       14762, 16088, 15060, 13156, 13619, 16241, 16106, 13706, 17634,
       15004])

### Quantity	

Generate numbers for quantity. As 75% of the datapoints had a quantity of 12, I will generate the number between 1 and 14.

In [11]:
#Quantity
#count 39184.000000
#mean 14.616246
#std 378.059152
#25% 2.000000
#50% 5.000000
#75% 12.000000
#max 74215.000000

quantity = np.random.choice(a=range(1, 14), size=size)
quantity

array([ 6,  8, 13, 13,  3,  2, 12, 10,  3, 10,  9, 10, 13,  4,  3, 11,  4,
       13,  1, 11, 12,  3, 10,  7, 11,  7,  1,  4, 13,  5,  9,  7, 10, 11,
        7, 11, 12, 13,  4, 13,  8,  8,  1,  7,  1,  1,  9,  8, 10,  2,  1,
       11,  3,  3,  1,  5,  2, 12,  7,  8,  4,  8,  4, 13, 11, 11, 13, 11,
       13,  3,  6,  6, 13,  6,  2,  2, 11,  5,  1,  9,  1,  9, 11,  6, 13,
       10, 13,  2,  6, 13,  8, 10, 11, 13, 13, 11,  9,  5,  3, 12])

### Unit Price

Generate a number with two digits to replicate the unit price. For example: 2.55

In [12]:
unitprice = np.round(np.random.normal(loc=2.90, scale=0.5, size=size), 2)
unitprice

array([2.86, 2.17, 3.68, 2.83, 3.52, 3.14, 3.08, 2.94, 3.02, 2.69, 3.09,
       2.42, 3.61, 2.83, 2.04, 3.13, 3.25, 3.37, 3.22, 2.98, 3.24, 3.89,
       2.73, 2.6 , 3.61, 2.87, 3.72, 2.91, 2.67, 3.63, 3.07, 3.77, 3.14,
       3.28, 2.96, 2.84, 3.36, 3.04, 3.85, 2.81, 2.76, 2.23, 2.85, 2.34,
       3.38, 2.72, 2.55, 2.85, 3.34, 2.25, 3.4 , 2.51, 2.59, 3.07, 2.99,
       2.73, 2.83, 2.35, 2.93, 2.74, 2.49, 2.73, 3.91, 3.22, 3.39, 3.25,
       4.02, 2.97, 3.1 , 3.76, 2.99, 2.19, 2.78, 3.02, 3.9 , 2.41, 2.72,
       4.42, 3.11, 2.68, 2.51, 2.31, 3.26, 2.75, 2.49, 2.35, 2.76, 2.65,
       3.35, 3.34, 2.75, 3.05, 2.98, 3.28, 3.6 , 4.  , 3.62, 2.22, 2.58,
       2.46])

### Invoice Date

Generate Date range between the dates: 12/01/2010 and 01/31/2011. Example: 2010-12-01 08:26:00

In [85]:
# adapted from https://pandas.pydata.org/pandas-docs/stable/timeseries.html
rng = pd.date_range('12/01/2010', '01/31/2011', periods=100)

# To remove the extra decimal places
invoicedatedata = pd.Series(rng).dt.round("s")
invoicedatedata

0    2010-12-01 00:00:00
1    2010-12-01 14:47:16
2    2010-12-02 05:34:33
3    2010-12-02 20:21:49
4    2010-12-03 11:09:05
5    2010-12-04 01:56:22
6    2010-12-04 16:43:38
7    2010-12-05 07:30:55
8    2010-12-05 22:18:11
9    2010-12-06 13:05:27
10   2010-12-07 03:52:44
11   2010-12-07 18:40:00
12   2010-12-08 09:27:16
13   2010-12-09 00:14:33
14   2010-12-09 15:01:49
15   2010-12-10 05:49:05
16   2010-12-10 20:36:22
17   2010-12-11 11:23:38
18   2010-12-12 02:10:55
19   2010-12-12 16:58:11
20   2010-12-13 07:45:27
21   2010-12-13 22:32:44
22   2010-12-14 13:20:00
23   2010-12-15 04:07:16
24   2010-12-15 18:54:33
25   2010-12-16 09:41:49
26   2010-12-17 00:29:05
27   2010-12-17 15:16:22
28   2010-12-18 06:03:38
29   2010-12-18 20:50:55
             ...        
70   2011-01-13 03:09:05
71   2011-01-13 17:56:22
72   2011-01-14 08:43:38
73   2011-01-14 23:30:55
74   2011-01-15 14:18:11
75   2011-01-16 05:05:27
76   2011-01-16 19:52:44
77   2011-01-17 10:40:00
78   2011-01-18 01:27:16


### Country
Generate Country from the list of 22 countries

In [19]:
country = ['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain']

countries = [np.random.choice(country) for i in range(size)]

### 4. Detail your research and implement the simulation in a Jupyter notebook – the data set itself can simply be displayed in an output cell within the notebook.

### Creating a Dataframe

In [86]:
mydict = { "InvoiceNo":invoice, "Description": description, 'Quantity': quantity, 
          "InvoiceDate":invoicedatedata, 'UnitPrice':unitprice, "CustomerID":CustomerID, "Country":countries}

df = pd.DataFrame(mydict, 
                  columns=['InvoiceNo', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country'])

df

InvoiceNo                                        Description  \
0  2011-01-29 04:00:00                       SET 7 BABUSHKA NESTING BOXES   
1  2011-01-07 22:00:00                                DOORMAT NEW ENGLAND   
2  2011-01-28 20:00:00                       BLUE COAT RACK PARIS FASHION   
3  2011-01-03 15:00:00                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
4  2011-01-13 06:00:00                     YELLOW COAT RACK PARIS FASHION   
5  2011-01-09 06:00:00                      RED WOOLLY HOTTIE WHITE HEART   
6  2011-01-24 10:00:00                          HAND WARMER RED POLKA DOT   
7  2010-12-21 03:00:00                       BOX OF VINTAGE JIGSAW BLOCKS   
8  2011-01-13 18:00:00                           HOME BUILDING BLOCK WORD   
9  2011-01-18 19:00:00                      RED WOOLLY HOTTIE WHITE HEART   
10 2011-01-16 05:00:00                      ASSORTED COLOUR BIRD ORNAMENT   
11 2010-12-15 11:00:00                     CREAM CUPID HEARTS COAT HANGER   
12 2010-12-21 15:00:00                            POPPY PLAYHOUSE BEDROOM   
13 2010-12-06 10:00:00                           HOME BUILDING BLOCK WORD   
14 2010-12-07 12:00:00                           HOME BUILDING BLOCK WORD   
15 2010-12-02 21:00:00                 WHITE HANGING HEART T-LIGHT HOLDER   
16 2010-12-09 16:00:00                             IVORY KNITTED MUG COSY   
17 2011-01-04 09:00:00                     BOX OF VINTAGE ALPHABET BLOCKS   
18 2010-12-29 07:00:00                       BOX OF VINTAGE JIGSAW BLOCKS   
19 2010-12-21 06:00:00                           LOVE BUILDING BLOCK WORD   
20 2010-12-12 09:00:00  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
21 2011-01-22 22:00:00                       BLUE COAT RACK PARIS FASHION   
22 2010-12-26 19:00:00  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
23 2010-12-03 03:00:00                     BOX OF VINTAGE ALPHABET BLOCKS   
24 2010-12-30 23:00:00                            POPPY PLAYHOUSE BEDROOM   
25 2011-01-09 14:00:00                           HOME BUILDING BLOCK WORD   
26 2011-01-21 09:00:00  GLASS STAR FROSTED T-LIGHT HOLDERHAND WARMER U...   
27 2010-12-13 20:00:00                       BLUE COAT RACK PARIS FASHION   
28 2011-01-23 05:00:00                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
29 2010-12-11 16:00:00                       BOX OF VINTAGE JIGSAW BLOCKS   
..                 ...                                                ...   
70 2011-01-03 01:00:00                          HAND WARMER RED POLKA DOT   
71 2011-01-24 10:00:00                                WHITE METAL LANTERN   
72 2010-12-10 11:00:00                          HAND WARMER RED POLKA DOT   
73 2010-12-01 02:00:00                           LOVE BUILDING BLOCK WORD   
74 2010-12-21 22:00:00                 WHITE HANGING HEART T-LIGHT HOLDER   
75 2010-12-07 17:00:00                                DOORMAT NEW ENGLAND   
76 2010-12-31 20:00:00                                DOORMAT NEW ENGLAND   
77 2011-01-13 15:00:00                           JAM MAKING SET WITH JARS   
78 2010-12-21 05:00:00                 WHITE HANGING HEART T-LIGHT HOLDER   
79 2011-01-22 12:00:00                           JAM MAKING SET WITH JARS   
80 2011-01-23 06:00:00                     BOX OF VINTAGE ALPHABET BLOCKS   
81 2011-01-06 23:00:00                       BOX OF VINTAGE JIGSAW BLOCKS   
82 2011-01-09 19:00:00                 WHITE HANGING HEART T-LIGHT HOLDER   
83 2010-12-03 22:00:00                           JAM MAKING SET WITH JARS   
84 2011-01-17 00:00:00                          HAND WARMER RED POLKA DOT   
85 2010-12-20 19:00:00                      ASSORTED COLOUR BIRD ORNAMENT   
86 2011-01-16 14:00:00                       SET 7 BABUSHKA NESTING BOXES   
87 2010-12-27 08:00:00                 BOX OF 6 ASSORTED COLOUR TEASPOONS   
88 2011-01-13 09:00:00                     YELLOW COAT RACK PARIS FASHION   
89 2011-01-07 20:00:00                       BLUE COAT RACK PARIS FASHION   
90 2010-1